export const fakeData = [
    {
        pageName: 'test1',
        beforeScore: 10,
        afterScore: 32,
        efficiency: 52,
        createTime: '2021-03-02',
    },
    {
        pageName: 'test2',
        beforeScore: 9,
        afterScore: 68,
        efficiency: 89,
        createTime: '2021-03-05',
    },
    {
        pageName: 'test3',
        beforeScore: 9,
        afterScore: 22,
        efficiency: 45,
        createTime: '2021-03-05',
    },
    {
        pageName: 'test4',
        beforeScore: 9,
        afterScore: 76,
        efficiency: 98,
        createTime: '2021-03-07',
    },
    {
        pageName: 'test5',
        beforeScore: 9,
        afterScore: 23,
        efficiency: 67,
        createTime: '2021-03-08',
    },
    {
        pageName: 'test6',
        beforeScore: 9,
        afterScore: 45,
        efficiency: 78,
        createTime: '2021-03-19',
    },
    {
        pageName: 'test7',
        beforeScore: 30,
        afterScore: 48,
        efficiency: 60,
        createTime: '2021-03-22',
    },
];
